addons:
  apt:
    packages:
      - texlive-latex-extra
      - cm-super
install: true
script: make && mkdir build && mv lawguide.pdf build/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
